version: '3.8'

services:
  app:
    image: my-library-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__LibraryContext="Data Source=/app/LibraryContext-b0a2225d-c8e3-40b1-864f-fc5a222cc01c.db"
    volumes:
      - ./app:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge